# Generated by Django 5.0 on 2023-12-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=50)),
                ('content', models.TextField(max_length=200)),
                ('related_board', models.ManyToManyField(blank=True, to='boards.board')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
